{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "common.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "api.names.fullname" . }}
  namespace: {{ include "api.names.namespace" . }}
  labels: {{- include "api.labels.standard" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (include "common.ingress.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ printf "%s-tls" (include "api.names.fullname" .) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if include "common.ingress.supportsPathType" . }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "api.names.fullname" .) "servicePort" "http") | nindent 14 }}
{{- end }}
