{{- if .Values.networkPolicy.enabled -}}
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "api.names.fullname" . }}
  namespace: {{ include "api.names.namespace" . }}
  labels: {{- include "api.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "api.labels.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    {{- if .Values.networkPolicy.allowExternalEgress }}
    - {}
    {{- else }}
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if .Values.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.extraEgress "context" $) | nindent 4 }}
    {{- end }}
    {{- end }}
  ingress:
    - ports:
        - port: {{ .Values.containerPorts.http }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels: {{- include "api.labels.matchLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              {{ include "api.names.fullname" . }}-client: "true"
        {{- if .Values.networkPolicy.ingressNSMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- if .Values.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- if .Values.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.extraIngress "context" $) | nindent 4 }}
    {{- end }}
{{- end }}
