{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api.names.fullname" . }}
  namespace: {{ include "api.names.namespace" . }}
  labels: {{- include "api.labels.standard" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.labels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metrics.serviceMonitor.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "api.labels.matchLabels" . | nindent 6 }}
  {{- if .Values.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.serviceMonitor.namespaceSelector "context" $) | nindent 4 }}
  {{- end }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
